In [4]:
import numpy as np

In [5]:
#1 : What is NumPy ? 
#Numpy is scientific computing library for python. 
#Support large number of data in the form of multidimensional array and matrix. 
#Use for mathematics calculation like linear algebra, Fourier transform and
#random number capabilities.  How to Represent Multidimensional array 

In [6]:
#1D Array 

In [39]:
arr = np.array([[1,2,3,4,5],[2,3,4,5,6],[9,7,6,8,9]])

In [40]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [41]:
arr.ndim

2

In [42]:
arr[0:2, 0:2]

array([[1, 2],
       [2, 3]])

In [43]:
arr[1:, 3:]

array([[5, 6],
       [8, 9]])

In [44]:
#Now u have to get output of 345 768

In [76]:
arr[0:3 , 2:5:1 ]

array([[3, 4, 5],
       [4, 5, 6],
       [6, 8, 9]])

In [64]:
arr[0:1, 2:] 


array([[3, 4, 5]])

In [58]:
arr[2 , 1:4]

array([7, 6, 8])

In [78]:
arr[0, 2:] +  [2 ,1,4]

array([5, 5, 9])

In [4]:
a = np.array([1,2,3]) 

In [5]:
a

array([1, 2, 3])

In [6]:
#2D Array 

In [7]:
a = np.array([  [1,2,3],  [1,2,3],  [1,2,3] ]) #list of list a 

In [8]:
a

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [9]:
#3D Array 

In [10]:
a = np.array([ [[1,2,3],[1,2,3],[1,2,3]],  [[1,2,3],[1,2,3],[1,2,3]], [[1,2,3],[1,2,3],[1,2,3]] ]) #list of list of list 

In [11]:
a

array([[[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]])

In [12]:
#Numpy vs Python List 
#Written in c & Python 
#Fast Process 
#Use less memory to store data 

In [13]:
#2 : How To Create a Array

In [14]:
array_1d = np.array([1,2,3,4,5])  

In [15]:
array_1d

array([1, 2, 3, 4, 5])

In [16]:
array_1d.ndim # ndim will show the dimention

1

In [17]:
 print(type(array_1d))  #find array type  print(type(array_1d)) 

<class 'numpy.ndarray'>


In [18]:
array_1d.shape 

(5,)

In [19]:
array_1d.size 

5

In [20]:
a = np.array([[[1,2,3,4],[10,20,30,40]],[[5,6,7,8],[50,60,70,80]]]) 

In [21]:
a

array([[[ 1,  2,  3,  4],
        [10, 20, 30, 40]],

       [[ 5,  6,  7,  8],
        [50, 60, 70, 80]]])

In [22]:
a.size

16

In [23]:
array_1d.dtype 

dtype('int32')

In [24]:
a.shape 

(2, 2, 4)

In [25]:
array_2d = np.array([[10,20,30,40],[11,22,33,77],[44,55,66,88]]) 

In [26]:
array_2d

array([[10, 20, 30, 40],
       [11, 22, 33, 77],
       [44, 55, 66, 88]])

In [27]:
array_2d.ndim  #ndim tells the dimension

2

In [28]:
array_2d.shape 

(3, 4)

In [29]:
array_2d.size

12

In [30]:
array_3d = np.array([  [ 
 [10,20,30,40],  [11,22,33,77],  [44,55,66,88],  ], 
 [ 
 [10,20,30,40],  [11,22,33,77],  [44,55,66,88],  ], 
 [ 
 [10,20,30,40],  [11,22,33,77],  [44,55,66,88],  ] ])

In [31]:
array_3d

array([[[10, 20, 30, 40],
        [11, 22, 33, 77],
        [44, 55, 66, 88]],

       [[10, 20, 30, 40],
        [11, 22, 33, 77],
        [44, 55, 66, 88]],

       [[10, 20, 30, 40],
        [11, 22, 33, 77],
        [44, 55, 66, 88]]])

In [32]:
array_3d.ndim 

3

In [33]:
array_3d.shape

(3, 3, 4)

In [34]:
array_3d.size 

36

In [35]:
#Create ones matrix 

In [36]:
two = np.array([[2,2,2],[2,2,2],[2,2,2]])

In [37]:
two

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [38]:
print(type(two))

<class 'numpy.ndarray'>


In [39]:
two.flatten() #flatten will convert any metrics to one dimentional array

array([2, 2, 2, 2, 2, 2, 2, 2, 2])

In [40]:
ones = np.array([[1,1,1],[1,1,1],[1,1,1]]) 

In [41]:
ones

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [42]:
ones_array = np.ones(15) 

In [43]:
ones_array

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [44]:
ones_array.ndim 

1

In [45]:
ones_array.ndim 

1

In [46]:
ones_array.dtype #bydefault creating a float value ones function in array 

dtype('float64')

In [47]:
#2D ones matrix 
ones_2dmx = np.ones((3,4), dtype='int') 

In [48]:
ones_2dmx 

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [49]:
ones_2dmx = np.ones((3,3,4), dtype='str')

In [50]:
ones_2dmx 

array([[['1', '1', '1', '1'],
        ['1', '1', '1', '1'],
        ['1', '1', '1', '1']],

       [['1', '1', '1', '1'],
        ['1', '1', '1', '1'],
        ['1', '1', '1', '1']],

       [['1', '1', '1', '1'],
        ['1', '1', '1', '1'],
        ['1', '1', '1', '1']]], dtype='<U1')

In [51]:
#Create a zeros matrix 

In [52]:
zeros_mx = np.zeros((3,3,4), dtype='str') 

In [53]:
zeros_mx 

array([[['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', '']],

       [['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', '']],

       [['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', '']]], dtype='<U1')

In [54]:
zeros_mx = np.zeros((4,4), dtype='int') 

In [55]:
zeros_mx

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [56]:
zeros_mx = np.zeros((4,4), dtype=bool)

In [57]:
zeros_mx

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [58]:
#range() function 

In [59]:
#synatx : arange([start,] stop[, step,], dtype=None) 2 
Range = np.arange(0,6).reshape(3,2) 

In [60]:
Range 

array([[0, 1],
       [2, 3],
       [4, 5]])

In [61]:
Range = np.arange(2,21,2).reshape(5,2) 

In [62]:
Range

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16],
       [18, 20]])

In [63]:
# linespace()

In [64]:
# Syntax : np.linspace(start,stop,num=50,endpoint=True, 2 
# retstep=False,dtype=None,axis=0) 3 
Linesp = np.linspace(1,10,5 ,endpoint=True, retstep=True, axis=0) 

In [65]:
Linesp

(array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ]), 2.25)

In [66]:
Linesp = np.linspace(1,10,10, endpoint=False, retstep=True) 

In [67]:
Linesp

(array([1. , 1.9, 2.8, 3.7, 4.6, 5.5, 6.4, 7.3, 8.2, 9.1]), 0.9)

In [68]:
Linesp = np.linspace(1,10,10, endpoint=True, retstep=True) 

In [69]:
Linesp

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), 1.0)

In [70]:
#reshape() 

In [71]:
# np.reshape(a, newshape,) 
array_1d = np.array([1,2,3,4,5,6,7,8]) 

In [72]:
array_1d 

array([1, 2, 3, 4, 5, 6, 7, 8])

In [73]:
Reshape2d = array_1d.reshape(2,2,2) 

In [74]:
Reshape2d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [75]:
Reshape3d=array_1d.reshape(1,8,1) #for layer 1 2

In [76]:
Reshape3d

array([[[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8]]])

In [77]:
Reshape3d = array_1d.reshape(2,1,4) #for layer 2 2 

In [78]:
Reshape3d

array([[[1, 2, 3, 4]],

       [[5, 6, 7, 8]]])

In [79]:
#use arange function with reshape or viceversa 2 
Reshape1 = np.arange(1,10).reshape(3,3) 

In [80]:
Reshape1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [81]:
Reshape1 = np.arange(1,10).reshape(1,3,3) 

In [82]:
Reshape1

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [83]:
Reshape1 = np.arange(1,28).reshape(3,3,3) 

In [84]:
Reshape1

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [85]:
#convert multidimensnioanl array in one dimensnioanl

In [86]:
Reshape1.ravel(order='A') # 'A' 1,2,3... in order

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [87]:
Reshape1.ravel(order='F') #"F" not in order

array([ 1, 10, 19,  4, 13, 22,  7, 16, 25,  2, 11, 20,  5, 14, 23,  8, 17,
       26,  3, 12, 21,  6, 15, 24,  9, 18, 27])

In [88]:
Reshape1.ravel(order='K')

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [89]:
Reshape1.ravel(order='C')

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [90]:
#flatten()

In [91]:
Reshape1.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [92]:
Reshape1.flatten(order='C')

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [93]:
Reshape1.flatten(order='F')

array([ 1, 10, 19,  4, 13, 22,  7, 16, 25,  2, 11, 20,  5, 14, 23,  8, 17,
       26,  3, 12, 21,  6, 15, 24,  9, 18, 27])

In [94]:
#transpose() # convert rows into colimn or viceversa

In [95]:
Reshape1.transpose()

array([[[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]],

       [[ 3, 12, 21],
        [ 6, 15, 24],
        [ 9, 18, 27]]])

In [96]:
Reshape1.T

array([[[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]],

       [[ 3, 12, 21],
        [ 6, 15, 24],
        [ 9, 18, 27]]])

In [97]:
print(Reshape1)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [98]:
#Numpy Operation

In [99]:
array1 = np.arange(1,13).reshape(4,3)
array2 = np.arange(1,13).reshape(4,3)

In [100]:
print(array1)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [101]:
print(array2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [102]:
#addition
array1+array2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18],
       [20, 22, 24]])

In [103]:
#add()
np.add(array1, array2)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18],
       [20, 22, 24]])

In [104]:
#subtract()
np.subtract(array1, array2)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [105]:
#multiply()
np.multiply(array1, array2)

array([[  1,   4,   9],
       [ 16,  25,  36],
       [ 49,  64,  81],
       [100, 121, 144]])

In [106]:
#divide()
np.divide(array1, array2)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [107]:
#matrix product
#addition of column and rows
ar1 = np.arange(1,10).reshape(3,3)
ar2 = np.arange(1,10).reshape(3,3)
print(ar1)
print(ar2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [108]:
1+2+3+4+5+6+7+8+9

45

In [109]:
ar1.dot(ar2) # 1+8+21=30 like vise multiply first row first coloum then add+ it

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [110]:
#max()
#find maximum value in the matrix
ar1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [111]:
ar1.max()

9

In [112]:
#argmax()
#find index of the maximum value
ar1.argmax()

8

In [113]:
aa = np.random.randint(1,10,9).reshape(3,3)

In [114]:
aa

array([[6, 2, 7],
       [9, 3, 3],
       [4, 8, 5]])

In [115]:
aa.max(), aa.argmax()

(9, 3)

In [116]:
#find maximum value in columns and rows using axis parameter
# 0 Represent columns and 1 represent Rows
ar1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [117]:
ar1.max(axis=0) #max in columns

array([7, 8, 9])

In [118]:
ar1.max(axis=1) #max in rows

array([3, 6, 9])

In [119]:
#sum()
#syntax:
#np.sum(a,axis=None,dtype=None)
ar1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [120]:
ar1.sum()

45

In [121]:
a = np.sum(ar1, axis=0) #addition of columns

In [122]:
a

array([12, 15, 18])

In [123]:
a = np.sum(ar1, axis=1) #addition of rows

In [124]:
a

array([ 6, 15, 24])

In [125]:
#mean()
#Find average value in the matyrix
ar1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [126]:
#addition of all element and divide by number of elements
ar1.mean()

5.0

In [127]:
#sqrt() & square()
#e.g. 9 square root 3 and 3 square 9
ar1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [128]:
np.sqrt(ar1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [129]:
np.square(ar1)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]], dtype=int32)

In [130]:
#std()
#find standard deviation
np.std(ar1)

2.581988897471611

In [131]:
#exp()
#find exponent
np.exp(ar1)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [132]:
#log() and logbase10=log10
np.log(ar1)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [133]:
np.log10(ar1)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251]])

In [134]:
#Array Slicing in Numpy

In [135]:
mx = np.arange(1,26).reshape(5,5)
mx

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [136]:
#print 1 element -1D
mx[0,0]

1

In [137]:
#check dimension
mx[0,0].ndim

0

In [138]:
#single rows - 2D
mx[0:1,0:6]

array([[1, 2, 3, 4, 5]])

In [139]:
#single columns
mx[0:6,0:1]

array([[ 1],
       [ 6],
       [11],
       [16],
       [21]])

In [140]:
#find random number
mx

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [141]:
# [13,14
# 18,19]
mx[2:4,2:4]

array([[13, 14],
       [18, 19]])

In [142]:
#use step parameters
# [7,9
# 17,19]
mx[1:4:2, 1:4:2]

array([[ 7,  9],
       [17, 19]])

In [143]:
#size of the item
mx.itemsize

4

In [144]:
mx.dtype

dtype('int32')

In [145]:
#Array Concatenation and Split
a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(10,19).reshape(3,3)

In [146]:
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [147]:
a2

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [148]:
a1+a2

array([[11, 13, 15],
       [17, 19, 21],
       [23, 25, 27]])

In [149]:
#use concatenate
np.concatenate((a1,a2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [150]:
np.concatenate((a1,a2), axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [151]:
np.concatenate((a1,a2)).T

array([[ 1,  4,  7, 10, 13, 16],
       [ 2,  5,  8, 11, 14, 17],
       [ 3,  6,  9, 12, 15, 18]])

In [152]:
#verical concate
np.vstack((a1,a2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [153]:
#horizantal concate
np.hstack((a1,a2))

array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 13, 14, 15],
       [ 7,  8,  9, 16, 17, 18]])

In [154]:
#Split
split_array = np.arange(1,25).reshape(6,4)
split_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [155]:
np.split(split_array,2)

[array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]])]

In [156]:
#split with columns
np.split(split_array, 2, axis=1)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [17, 18],
        [21, 22]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16],
        [19, 20],
        [23, 24]])]

In [157]:
#Trignometry sin(), cos(), tan()
np.sin(180) #in degree

-0.8011526357338304

In [158]:
np.sin(90)

0.8939966636005579

In [159]:
np.tan(180)

1.3386902103511544

In [160]:
np.tan(360)

-3.380140413960958

In [161]:
np.cos(180)

-0.5984600690578581

In [162]:
#5 : Random Sampling
import random
import numpy as np

In [163]:
#random()
np.random.random(2)

array([0.52508733, 0.93459321])

In [164]:
#in array
np.random.random((3,3))

array([[0.82404631, 0.38567867, 0.49609751],
       [0.96820026, 0.68175797, 0.82972223],
       [0.0859455 , 0.00315691, 0.19133466]])

In [165]:
#randint()
np.random.randint(3)

2

In [166]:
np.random.randint(1,3,20)

array([2, 2, 1, 1, 1, 2, 1, 2, 1, 2, 1, 2, 2, 2, 2, 2, 2, 2, 1, 2])

In [167]:
np.random.randint(1,3,(5,4))

array([[1, 2, 2, 2],
       [1, 1, 2, 1],
       [1, 2, 2, 1],
       [1, 2, 1, 2],
       [2, 2, 2, 2]])

In [168]:
#in 3D shape
np.random.randint(1,3,(2,5,4))

array([[[1, 2, 1, 2],
        [1, 2, 1, 2],
        [2, 1, 2, 1],
        [2, 2, 1, 2],
        [2, 1, 1, 2]],

       [[1, 1, 1, 2],
        [2, 1, 2, 2],
        [2, 2, 2, 1],
        [2, 1, 2, 2],
        [2, 1, 2, 1]]])

In [169]:
#seed()
#in 3D shape..using seed function for does not change values of matrix
np.random.seed(10)
np.random.randint(1,3,(5,4))

array([[2, 2, 1, 2],
       [1, 2, 2, 1],
       [2, 2, 1, 2],
       [2, 1, 1, 2],
       [1, 1, 1, 1]])

In [170]:
#in 3D shape..using seed function for does not change values of matrix
np.random.seed(10)
np.random.randint(1,3,(5,4))

array([[2, 2, 1, 2],
       [1, 2, 2, 1],
       [2, 2, 1, 2],
       [2, 1, 1, 2],
       [1, 1, 1, 1]])

In [171]:
#6 : String operation, Comparison and Information
str1 = "I am a python developer"
str2 = " I learn new Technology"

In [172]:
#char.add()
np.char.add(str1,str2)

array('I am a python developer I learn new Technology', dtype='<U46')

In [173]:
np.char.multiply(str1,2)

array('I am a python developerI am a python developer', dtype='<U46')

In [174]:
#char.lower()
np.char.lower(str1)

array('i am a python developer', dtype='<U23')

In [175]:
np.char.upper(str1)

array('I AM A PYTHON DEVELOPER', dtype='<U23')

In [176]:
#char.center()
np.char.center(str1, 30)

array('   I am a python developer    ', dtype='<U30')

In [177]:
np.char.center(str1, 30, fillchar="$")

array('$$$I am a python developer$$$$', dtype='<U30')

In [178]:
#char.split()
np.char.split(str1)

array(list(['I', 'am', 'a', 'python', 'developer']), dtype=object)

In [179]:
np.char.splitlines("hello\nworld")

array(list(['hello', 'world']), dtype=object)

In [180]:
#char.join()
st1 = 'DMY'
st2='dmy'
st3 = 'DmY'
np.char.join([":","/","-"], [st1,st2,st3])

array(['D:M:Y', 'd/m/y', 'D-m-Y'], dtype='<U5')

In [181]:
#char.replace()
str1

'I am a python developer'

In [182]:
np.char.replace(str1, "am", "Am")

array('I Am a python developer', dtype='<U23')

In [183]:
#char.equal() -
#for comparision
st1,st2,
st3='DMY'

In [184]:
np.char.equal(st1,st3)

array(True)

In [185]:
#char.count()
np.char.count(str1, "a"), str1

(array(2), 'I am a python developer')

In [186]:
#char.find()
np.char.find(str1, "o")

array(11)

In [187]:
#BroadCasting
#Broadcasting allows these types of binary operations to be performed on arrays of different sizes–for example,
#we can just as easily add a scalar (think of it as a zero-dimensional array) to an array:
a = np.array([0, 1, 2])
b = np.array([5, 5, 5])

In [188]:
a+b

array([5, 6, 7])

In [189]:
a+7

array([7, 8, 9])

In [190]:
c = np.ones((3,3))
c

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [191]:
a.ndim, c.ndim

(1, 2)

In [192]:
a.shape, c.shape

((3,), (3, 3))

In [193]:
a+c

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [194]:
#columns shape not same
d= np.ones((3,2))

In [195]:
d

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [196]:
a+d

ValueError: operands could not be broadcast together with shapes (3,) (3,2) 

In [197]:
#columns shape same
d= np.ones((2,3))

In [198]:
d

array([[1., 1., 1.],
       [1., 1., 1.]])

In [199]:
##Broadcasting with 2d

In [200]:
c

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [201]:
d

array([[1., 1., 1.],
       [1., 1., 1.]])

In [202]:
c+d

ValueError: operands could not be broadcast together with shapes (3,3) (2,3) 

In [203]:
c.ndim, d.ndim

(2, 2)

In [204]:
c.shape, d.shape

((3, 3), (2, 3))

In [205]:
#transpose in 3,2
d.T

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [206]:
c+(d.T)

ValueError: operands could not be broadcast together with shapes (3,3) (3,2) 

In [207]:
#shape same
e = np.ones((3,3))

In [208]:
e

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [209]:
c+e

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [210]:
#Braodcasting

In [211]:
np.arange(3)+5

array([5, 6, 7])

In [212]:
np.ones((3,3))+np.arange(3)

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [213]:
np.arange(3).reshape((3,1))+np.arange(3)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [214]:
np.arange(5)+4

array([4, 5, 6, 7, 8])

In [215]:
np.arange(3)+np.arange(3).reshape((3,1))

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [216]:
np.arange(15).reshape((3,5))+np.arange(5)

array([[ 0,  2,  4,  6,  8],
       [ 5,  7,  9, 11, 13],
       [10, 12, 14, 16, 18]])

In [217]:
#BC in 3D : 1d + 3d
d3 = np.arange(1,9).reshape(2,2,2)
d3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [218]:
d1 = np.array([10,20])
d1

array([10, 20])

In [219]:
d3+d1

array([[[11, 22],
        [13, 24]],

       [[15, 26],
        [17, 28]]])

In [220]:
#BC 2d + 3d
d2 = np.arange(1,5).reshape(2,2)

In [221]:
d2

array([[1, 2],
       [3, 4]])

In [222]:
d3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [223]:
d3+d2

array([[[ 2,  4],
        [ 6,  8]],

       [[ 6,  8],
        [10, 12]]])

In [224]:
#shape not same
d2 = np.arange(1,5).reshape(4,1)
d2

array([[1],
       [2],
       [3],
       [4]])

In [225]:
#Rules of Broadcasting
#Broadcasting in NumPy follows a strict set of rules to determine the interaction between the two arrays:
#Rule 1: If the two arrays differ in their number of dimensions, the shape of the one with fewer dimensions is padded with 
#ones on its leading (left) side.
#Rule 2: If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in
#that dimension is stretched to match the other shape.
#Rule 3: If in any dimension the sizes disagree and neither is equal to 1, an error is raised.